PhoenixWeb.Site/Controllers/AjaxAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PhoenixObjects.Common;
using Phoenix_BusLog.Data;
using PhoenixObjects.Member;
using PhoenixObjects.Administrator;
using PhoenixObjects.UserAuthentication;
using PhoenixObjects.Terminal;

namespace PhoenixWeb.Controllers
{
    [Authorize]
    public class AjaxAdminController : Controller
    {
        public JsonResult GetCountries()
        {
            CountryDA cda = new CountryDA();

            var countries = cda.Get().ToList();
            countries.Add(new CountryModel
            {
                CountryKey = 0,
                CountryName = "Select Country"
            });
            return Json(countries.OrderBy(c => c.CountryKey), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetSearchFields()
        {
            MemberDA mda = new MemberDA();
            var SearchFieldList = mda.SearchField(string.Empty, string.Empty).ToList();
            return Json(SearchFieldList, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetMemberRentalTemplate(int company_key)
        {
            MemberRentalTemplateDA cda = new MemberRentalTemplateDA();

            var MemberRentalTemplateList = cda.GetByCompanyKey(company_key).ToList();
            MemberRentalTemplateList.Add(new MemberRentalTemplateModel
            {
                MemberRentalTemplateKey = 0,
                Description = "Select Member Rental Template"
            });
            return Json(MemberRentalTemplateList.OrderBy(c => c.Description), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTerminalRentalRateList(int MemberRentalTemplateKey)
        {
            Session["RateListToSave"] = null;
            TerminalRentalRateDA cda = new TerminalRentalRateDA();
            var TerminalRentalTemplateList = cda.GetByMemberRentalTemplateKey(MemberRentalTemplateKey).ToList();
            Session["RateListToSave"] = TerminalRentalTemplateList;
            return Json(TerminalRentalTemplateList.OrderBy(c => c.RentAmount), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBusinessType()
        {
            BusinessTypeDA cda = new BusinessTypeDA();

            var businessType = cda.Get().ToList();
            businessType.Add(new BusinessTypeModel
            {
                BusinessTypeKey = 0,
                BusinessTypeName = "Select Business Type"
            });
            return Json(businessType.OrderBy(c => c.BusinessTypeKey), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetVehicleType()
        {
            VehicleTypeDA cda = new VehicleTypeDA();
            var VehicleType = cda.Get().ToList();
           
            return Json(VehicleType.OrderBy(c => c.VehicleType_key), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetOffice()
        {
            OfficeDA oda = new OfficeDA();
            var office = oda.GetOffices().ToList();
            office.Add(new OfficeModel
            {
                Name = "Select Office",
                Office_key = 0
            });
            return Json(office.OrderBy(c => c.Office_key), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetUsers()
        {
            UserDA oda = new UserDA();
            var users = oda.GetUsers().ToList();
            users.Add(new UserProfileModel
            {
                UserName = "Select Users",
                UserId = Guid.Empty
            });
            return Json(users.OrderBy(c => c.UserName), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetRoles()
        {
            RolesDA rda = new RolesDA();
            var roles = rda.GetRoles().ToList();
            roles.Add(new RoleModel
            {
                RoleName = "Select Role",
                RoleId = Guid.Empty
            });
            return Json(roles.OrderBy(c => c.RoleId), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetDealers()
        {
            DealerDA cda = new DealerDA();
            var dealer = cda.Get().ToList();
            dealer.Add(new MemberModel
            {
                Member_key = 0,
                TradingName = "Select Dealer"
            });
            return Json(dealer.OrderBy(c => c.Member_key), JsonRequestBehavior.AllowGet);
        }
                
        public ActionResult GetRentalTurnoverRange()
        {
            RentalTurnOverDA cda = new RentalTurnOverDA();
            var RentalTurnoverRange = cda.Get().ToList();
            RentalTurnoverRange.Add(new RentalTurnOverModel
            {
                RentalTurnoverRangeKey = 0,
               RangeMsg = "Please select turnover range"
            });
            return Json(RentalTurnoverRange.OrderBy(c => c.RentalTurnoverRangeKey), JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetStates()
        {

            StateDA cda = new StateDA();
            var states = cda.GetStateAustralia().ToList();
            //states.Add(new StateModel
            //{
            //    StateKey = 0,
            //    StateName = "Select State"
            //});
            return Json(states.OrderBy(c => c.StateKey), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetEFTTerminalId(int termId)
        {
            TerminalDA cda = new TerminalDA();
            string teId = termId.ToString();
            var states = cda.CheckTerminalExists(teId);
            return Json(states.TerminalId, JsonRequestBehavior.AllowGet);
        }
     
    }
}

PhoenixWeb.Site/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Phoenix_BusLog;
using PhoenixObjects;
using System.IO;
using System.Text.RegularExpressions;
using PhoenixObjects.Member;
using Phoenix_BusLog.Data;
using PhoenixObjects.Common;
using System.Data.Entity.Validation;
using Phoenix_BusLog.Salesforce;
using SalesforceSharp;
using SalesforceSharp.Security;
using SalesforceSharp.Serialization;
using SalesforceSharp.Models;
using PhoenixObjects.Terminal;
using PhoenixObjects.Financial;
using System.Transactions;
using PhoenixObjects.Salesforce;
namespace PhoenixWeb.Controllers
{
    [Authorize(Roles = "Operations,Administrator")]
    public class MemberController : Controller
    {
        //
        // GET: /Administrator/Member/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Menu()
        {
            return View();

        }
      public  List<SAccount> recordAccountGlobalList = new List<SAccount>();
      public List<SContact> recordLeadGlobalList = new List<SContact>();
      public List<SLead> recordOpportGlobalList = new List<SLead>();

      private List<SAccount> SalesForceConnect(string sfName, string type)
      {
          var client = new SalesforceClient();
          //Setup > Personal Setup > My Personal Information > Reset My Security Token.
          SalesforceDA sda = new SalesforceDA();
          SalesforceDetailModel cred = new SalesforceDetailModel();
          cred = sda.GetCredentials();

          var authFlow = new UsernamePasswordAuthenticationFlow(cred.ClientID, cred.Secret, cred.UserName, cred.TokenPassword);
          client.Authenticate(authFlow);
          IList<SAccount> records = null;
          if (type == "1")
          {
              //order is important
              records = client.Query<SAccount>("SELECT Id, AccountNumber,Name,Description,Industry,ShippingCity,ShippingCountry,ShippingState,ShippingPostalCode,ShippingStreet,Phone FROM Account where Name like '" + sfName + "%'");
          }
          if (type == "2")
          {
              records = client.Query<SAccount>("SELECT Id, AccountNumber,Name,Description,Industry,ShippingCity,ShippingCountry,ShippingState,ShippingPostalCode,ShippingStreet,Phone FROM Account where Phone like '%" + sfName + "%'");
          }
          foreach (var r in records)
          {
              SAccount a = new SAccount();
              a.Id = r.Id;
              a.AccountNumber = r.AccountNumber;
              a.Name = r.Name;
              a.Description = r.Description;
              a.Industry = r.Industry;
              a.ShippingCity = r.ShippingCity;
              a.ShippingCountry = r.ShippingCountry;
              a.ShippingState = r.ShippingState;
              a.ShippingPostalCode = r.ShippingPostalCode;
              a.ShippingStreet = r.ShippingStreet;
              a.Phone = r.Phone;

              recordAccountGlobalList.Add(a);
          }
          Session["recordAccountGlobalList"] = recordAccountGlobalList;
          return recordAccountGlobalList;
      }

      private void SalesForceConnect2(string AccountId)
      {
          var client = new SalesforceClient();
          //Setup > Personal Setup > My Personal Information > Reset My Security Token.
          SalesforceDA sda = new SalesforceDA();
          SalesforceDetailModel cred = new SalesforceDetailModel();
          cred = sda.GetCredentials();

          var authFlow = new UsernamePasswordAuthenticationFlow(cred.ClientID, cred.Secret, cred.UserName, cred.TokenPassword);
          client.Authenticate(authFlow);

          IList<SContact> leadRecords = null;
          IList<SLead> lead = null;
          leadRecords = client.Query<SContact>("SELECT AccountId, FirstName, LastName,Email,MasterRecordId,Name,Birthdate,MailingCity,MailingCountry,MailingPostalCode,MailingState,MailingStreet,MobilePhone,Fax,Phone FROM Contact where AccountId = '" + AccountId + "'");
          lead = client.Query<SLead>("SELECT AccountId, Amex_Diners__c,Average_transaction__c,Diners__c,Debit__c,EFTPOS_turnover__c,Terminal_Rental__c,Visa_Mastercard__c,Monthly_Rental__c,Flat_Rate__c FROM Opportunity where AccountId = '" + AccountId + "'");
          foreach (var r in leadRecords)
          {
              SContact a = new SContact();
              a.AccountId = r.AccountId;
              a.FirstName = r.FirstName;
              a.LastName = r.LastName;
              a.Email = r.Email;
              a.MasterRecordId = r.MasterRecordId;
              a.Name = r.Name;
              a.MailingCity = r.MailingCity;
              a.MailingCountry = r.MailingCountry;
              a.MailingPostalCode = r.MailingPostalCode;
              a.MailingState = r.MailingState;
              a.MailingStreet = r.MailingStreet;
              a.MobilePhone = r.MobilePhone;
              a.Phone = r.Phone;
              a.Fax = r.Fax;
              recordLeadGlobalList.Add(a);
          }
          foreach (var r in lead)
          {
              SLead a = new SLead();
              a.AccountId = r.AccountId;
              a.Amex_Diners__c = r.Amex_Diners__c;
              a.Diners__c = r.Diners__c;
              a.Average_transaction__c = r.Average_transaction__c;
              a.Debit__c = r.Debit__c;
              a.EFTPOS_turnover__c = r.EFTPOS_turnover__c;
              //turn over range
              a.Terminal_Rental__c = r.Terminal_Rental__c;
              a.Visa_Mastercard__c = r.Visa_Mastercard__c;
             // a.Sliding_Scale__c = r.Sliding_Scale__c;
              a.Monthly_Rental__c = r.Monthly_Rental__c;
              a.Flat_Rate__c = r.Flat_Rate__c;

              recordOpportGlobalList.Add(a);
          }
      }
      public ActionResult SalesforceAddMemeber(string Id)
      {
          recordAccountGlobalList = (List<SAccount>)Session["recordAccountGlobalList"];
          SAccount ac = recordAccountGlobalList.Find(r => r.Id == Id);

          List<SForceModel> modelSF = new List<SForceModel>();
          SContact ld = new SContact();
          SLead led = new SLead();
          SalesForceConnect2(Id);

          if (ac != null)
          {
              SForceModel sforceModel = new SForceModel();
              ld = recordLeadGlobalList.Find(r => r.AccountId == Id);
              led = recordOpportGlobalList.Find(r => r.AccountId == Id);

              MemberModel mem = new MemberModel();
              mem.SalesforceId = Id;
              mem.CompanyKey = 18;

              if (ld != null)
              {
                  if (ld.FirstName != null)
                      mem.FirstName = ld.FirstName.Substring(0, 1).ToUpper() + ld.FirstName.Substring(1);
                  if (ld.LastName != null)
                      mem.LastName = ld.LastName.Substring(0, 1).ToUpper() + ld.LastName.Substring(1);
                  mem.Email = ld.Email;
                  if (ld.Phone != null)
                  {
                      string preMob = ld.Phone.Substring(0, 2);

                      if (preMob == "04")
                      {
                          mem.Mobile = ld.Phone.Trim();
                      }
                      else
                      {
                         mem.Telephone = ld.Phone.Trim();
                      }

                  }
                  if (ld.MobilePhone != null)
                      mem.Mobile = ld.MobilePhone.Trim();
                  mem.TradingName = ac.Name;
                  mem.Fax = ld.Fax;

                  if (Convert.ToDateTime(ld.Birthdate) != DateTime.MinValue)
                  {
                      mem.DOB = Convert.ToDateTime(ld.Birthdate);
                  }
              }

              if (led != null)
              {
                  if (led.Debit__c != null)
                      mem.CRDebitRate = led.Debit__c.Value;
                  if (led.Debit__c != null)
                      mem.CRDebitRatePercentage = led.Debit__c.Value;
                  if (led.Visa_Mastercard__c != null)
                      mem.CRVisaRate = led.Visa_Mastercard__c.Value;
                  if (led.Visa_Mastercard__c != null)
                      mem.CRMasterCardRate = led.Visa_Mastercard__c.Value;
                  if (led.Amex_Diners__c != null)
                      mem.CRAmexRate = led.Amex_Diners__c.Value;
                  if (led.Diners__c != null)
                      mem.CRDinersRate = led.Diners__c.Value;

                  string mRental = led.Monthly_Rental__c;
                  if (mRental != null)
                  {
                      MemberRentalTemplateDA mrda = new MemberRentalTemplateDA();
                      mem.RentalMemberRentalTemplateKey = mrda.GetKeyByName(mRental);
                  }

                  if (led.Flat_Rate__c != null)
                  {
                      mem.IsFlatRate = led.Flat_Rate__c;
                  }
                  else
                  {
                      mem.IsFlatRate = false;
                  }

                  if (led.Terminal_Rental__c != null)
                      mem.RentalAmountFromSalesforce = led.Terminal_Rental__c;

                  var range = led.EFTPOS_turnover__c;
                  RentalTurnOverDA rda = new RentalTurnOverDA();
                  if (range != null)
                      mem.RentalTurnoverRangeKeyFromSalesforce = rda.GetTurnOverRangeKey(range.Value);

              }
              else
              {

                  //no opportunities found in the salesforce so use default
                  CommissionRateDA cda = new CommissionRateDA();
                  DefaultRateModel drt = new DefaultRateModel();
                  drt = cda.GetDefaultCommissionRate(1, 1);

                  mem.CRDebitRate = drt.Debit;
                  mem.CRDebitRatePercentage = drt.DebitPercentage;
                  mem.CRVisaRate = drt.Visa;
                  mem.CRMasterCardRate = drt.Master;
                  mem.CRAmexRate = drt.Amex;

PhoenixWeb.Site/Views/Member/AddAllocateMemberTerminal.cshtml
@model PhoenixObjects.Member.TerminalAllocationModel

@{
    ViewBag.Title = "Allocate Terminal";
    Layout = "~/Views/Shared/_TerminalPopupLayout.cshtml";
    ViewBag.Action = "AllocateMemberTerminal";
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#SaleReps").autocomplete({
            source: '@Url.Action("AutoCompleteEmployee")'

        });
    });

    $(document).ready(function () {
        $("#EftTerminal_key").autocomplete({
            source: '@Url.Action("AutoCompleteEftTerminalId")'
        });
    });

</script>
<h3>Allocate Terminal</h3>
<h4 style="color:red">@ViewBag.Error</h4>
<table>
    <tr>
        <td>
            <b> @Html.DisplayNameFor(model => model.Member.MemberId) </b>
        </td>
        <td>
            @Html.DisplayFor(model => model.Member.MemberId)
        </td>
    </tr>
    <tr>
        <td>
            <b> @Html.DisplayNameFor(model => model.Member.FirstName) </b>
        </td>
        <td>
            @Html.DisplayFor(model => model.Member.FirstName)
        </td>
        <td>
            <b> @Html.DisplayNameFor(model => model.Member.LastName) </b>
        </td>
        <td>
            @Html.DisplayFor(model => model.Member.LastName)
        </td>
    </tr>
    <tr>
        <td>
            <b> @Html.DisplayNameFor(model => model.Member.Email) </b>
        </td>
        <td>
            @Html.DisplayFor(model => model.Member.Email)
        </td>
        <td>
            <b> @Html.DisplayNameFor(model => model.Member.Mobile) </b>
        </td>
        <td>
            @Html.DisplayFor(model => model.Member.Mobile)
        </td>
    </tr>
</table>
<hr />

      <table>
          <tr>
              <td>
                  <div class="editor-label">
                      <label>Business ID</label>
                  </div>
              </td>
              <td>
                  <div class="editor-field">
                      <input type="text" name="VehicleId" required id="VehicleId" />
                  </div>
              </td>
              <td>

                  <div class="editor-label">
                     <label>Business Type</label>
                  </div>
              </td>
              <td>
                 <div class="editor-field">
                     <select style="width: 310px;height:30px" id="VehicleType" name="VehicleType"></select>
                  </div>
              </td>
           
          </tr>
          <tr>
              <td>
                  <div class="editor-label">
                      <label>Business State</label>
                  </div>
              </td>
              <td>
                  <div class="editor-field">
                      <select style="width: 310px;height:30px" id="StateId" name="StateId"></select>
                  </div>
              </td>
              <td>

                  <div class="editor-label">
                      <label>Terminal ID</label>
                  </div>
              </td>
              <td>
                  <div class="editor-field">
                      <input type="number" name="EftTerminal_key" required id="EftTerminal_key" />
                  </div>
              </td>
          </tr>
          <tr>
              <td>
                  <div class="editor-label">
                      <label>Terminal Allocation Date</label>
                  </div>
              </td>
              <td>
                  <div class="editor-field">
                      <input type="date" name="TerminalAllocationDate" required id="TerminalAllocationDate" />
                  </div>
              </td>

              <td>
                  <div class="editor-label">
                      <label>Delivery Required</label>
                  </div>
              </td>
              <td>
                  <div class="editor-field">
                        @Html.EditorFor(model => model.DeliveryRequired)
                      @Html.ValidationMessageFor(model => model.DeliveryRequired)
                  </div>
              </td>
          </tr>

           <tr>
              <td>
                  <div class="editor-label">
                      <label>Default Service Fee</label>
                  </div>
              </td>
              <td>
                  <div class="editor-field">
                      @Html.EditorFor(model => model.ServiceFee)
                      @Html.ValidationMessageFor(model => model.ServiceFee)
                  </div>
              </td>

              <td>
                  <div class="editor-label">
                      <label>Allow MOTO</label>
                  </div>
              </td>
              <td>
                  <div class="editor-field">
                        @Html.EditorFor(model => model.AllowMOTO)
                      @Html.ValidationMessageFor(model => model.AllowMOTO)
                  </div>
              </td>
          </tr>
           <tr>
              <td>
                  <div class="editor-label">
                      <label>Allow Refund</label>
                  </div>
              </td>
              <td>
                  <div class="editor-field">
                        @Html.EditorFor(model => model.AllowRefund)
                      @Html.ValidationMessageFor(model => model.AllowRefund)
                  </div>
              </td>

              <td>
                  <div class="editor-label">
                      <label>Sale Reps</label>
                  </div>
              </td>
              <td>
                  <div class="editor-field">
                      <input type="text" name="SaleReps" placeholder="type name and select" id="SaleReps"/>

                  </div>
              </td>
          </tr>
      </table>
        <p>

        </p>
 @if(Model.Member.TerminalAllocationList != null)
    {
<hr />
<table>
   
    @if (Model.Member.TerminalAllocationList != null && Model.Member.TerminalAllocationList.Count() > 0)
    {
        
        <thead style="font-weight:300">
           Current Allocation List 
        </thead>
          <tr>
                <td>
                  <label>Terminal_key</label>
                </td>
              <td>
                  <label>Vehicle_key</label>
              </td>
                <td>
                    <label>Member_key</label>
                </td>
                <td>
                    <label>ServiceFee</label>
                </td>

                <td>
                    <label>Effective Date</label>
                </td>
                <td>
                    <label>Allow Moto</label>
                </td>
              <td>
                  <label>Allow Refund</label>
              </td>
            </tr>
        foreach (var item in Model.Member.TerminalAllocationList)
        {
            <tr>
               
                <td>
                    @Html.DisplayFor(modelItem => item.EftTerminal_key)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vehicle_key)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Member_key)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ServiceFee)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EffectiveDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AllowMOTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AllowRefund)
                </td>
                <td></td>
               
            </tr>
        }
    }
    
</table>
 }
<br />
@section scripts {
    <script type="text/javascript">

        $("#dialog").dialog({
            width: "1000"
        });

        $.ajax({
            url: '@Url.Action("GetVehicleType", "AjaxAdmin")',
            type: "GET",
            dataType: "json",
            success: function (data) {
               $.each(data, function (i, item) {
                    $("#VehicleType").append(
                            $("<option></option>").val(item.VehicleType_key).html(item.Name)
                        );
                });
            },
            error: function () {
                alert("Error loadng Vehicle Type!");
            }
        });

        $.ajax({
            url: '@Url.Action("GetStates", "AjaxAdmin")',
            type: "GET",
            dataType: "json",
            success: function (data1) {
                $.each(data1, function (i, item) {
                    $("#StateId").append(
                            $("<option></option>").val(item.StateName).html(item.StateName)
                        );
                });

            },
            error: function () {
                alert("Error loadng State!");
            }
        });


    </script>
}

PhoenixWeb.Site/Views/Member/CreateMemberRental.cshtml
@model PhoenixObjects.Member.MemberRentalModel

@{
    ViewBag.Title = "Add New Member Rental";
    ViewBag.Action = "CreateMemberRental";
    Layout = "~/Views/Shared/_RentalPopupLayout.cshtml";
}

@*<script type="text/javascript">
    $(document).ready(function () {
        $.getJSON("Phoenixweb/AjaxAdmin/GetRentalTurnoverRange", null, function (data) {
            $.each(data, function (i, item) {
                $("<option>").val(this.RentalTurnoverRangeKey)
                             .text(this.RangeMsg)
                             .appendTo("#RentalTurnoverRange");
            });
        });
    });
</script>*@
<h3>Add Member Rental</h3>
    <table>
    <tr>
        <td>
            <div class="editor-label">
                <label>Rent Free</label>
            </div>
        </td>
        <td>
            <div class="editor-field">
                @Html.EditorFor(model => model.RentFree)
                @Html.ValidationMessageFor(model => model.RentFree)
            </div>
        </td>
       
    </tr>
    <tr>
        <td>
            <div class="editor-label">
                <label>Start Date</label>
            </div>
        </td>
        <td>
            <div class="editor-field">
                 <input type="date" name="StartDate"  id="StartDate" />

            </div>
        </td>
        <td>

            <div class="editor-label">
                <label>End Date</label>
            </div>
        </td>
        <td>

            <div class="editor-field">
                 <input type="date" name="EndDate" id="EndDate" />
            </div>
        </td>
    </tr>

        <tr>
        <td>
            <div class="editor-label">
                <label>Rental Amount</label>
            </div>
        </td>
        <td>
            <div class="editor-field">
                <input type="number" name="RentalAmount" required id="RentalAmount" value="@Model.RentalAmount" />
            </div>
        </td>
        <td>

            <div class="editor-label">
                <label>Rental Turnover Range</label>
            </div>
        </td>
        <td>

            <div class="editor-field">
                <select style="width: 310px;height:30px" id="RentalTurnoverRange" name="RentalTurnoverRange"></select>
            </div>
        </td>
    </tr>

</table>


    @if (Model.MemberRentalModelList != null)
    {
        <hr />
<table>
    @if (Model.MemberRentalModelList != null && Model.MemberRentalModelList.Count() > 0)
    {
        <thead style="font-weight:300">
           Current Member Rental List 
        </thead>
        
          <tr>
                <td>
                  <label>Rental Free</label>
                </td>
                <td>
                    <label>Start Date</label>
                </td>
                <td>
                    <label>End Date</label>
                </td>

                <td>
                    <label>Rental Amount</label>
                </td>
                <td>
                    <label>Rental Turn Over</label>
                </td>
            </tr>
        foreach (var item in Model.MemberRentalModelList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RentFree)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.RentalAmount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RentalTurnoverRangeKey)
                </td>
               
            </tr>
        }
    }
    
</table>
    }
<br />
@section scripts {
    <script type="text/javascript">

    $("#dialog").dialog({
        width: "980"
    });

    $.ajax({
        url: '@Url.Action("GetRentalTurnoverRange", "AjaxAdmin")',
        type: "GET",
        dataType: "json",
        success: function (data) {
            $.each(data, function (i, item) {
                $("#RentalTurnoverRange").append(
                        $("<option></option>").val(item.RentalTurnoverRangeKey).html(item.RangeMsg)
                    );
            });

        }
    });

      
    </script>
}

PhoenixWeb.Site/Views/Member/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

PhoenixWeb.Site/Views/Member/List.cshtml
@model IEnumerable<PhoenixObjects.Member.MemberModel>

@{
    ViewBag.Title = "List";
  //  Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Member List</h2>

<table>
    <tr>
         <th>
            @Html.DisplayNameFor(model => model.Member_key)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
         <td>
            @Html.DisplayFor(modelItem => item.Member_key)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Member_key }) |
            @Html.ActionLink("Address", "AddMemberAddress", new { id = item.Member_key }) |
            @Html.ActionLink("Details", "Details", new { id = item.Member_key }) |
        </td>
    </tr>
}

</table>

PhoenixWeb.Site/Views/Member/Menu.cshtml
@{
    ViewBag.Title = "Menu";
  //  Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@*<script type="text/javascript">
     $(document).ready(function () {
         $("#CreateMember").hover(
         function () {
             $(this).attr("src", "~/Images/AddMemeber_hover.png");
             $(this).css('cursor', 'pointer');
         },
         function () {
             $(this).attr("src", "~/Images/AddMemeber.png");
             $(this).css('cursor', 'default');
         });
       
     });

     </script>*@

@*<h2 style="text-align:center">Member Menu</h2><br />*@
<table cellpadding:"5" align="center" width="70%">
    <tr>
        <td>
            <a href="@Url.Action("Create", "Member")"><img id="CreateMember" src="~/Images/AddMemeber.png" width:"50px" height:"30px"/></a>
        </td>
         <td>
            <a href="@Url.Action("Search", "Member")"><img src="~/Images/SearchMember.png" width:"50px" height:"30px"/></a>
        </td>
         <td>
            <a href="@Url.Action("SalesforceSearch", "Member")"><img src="~/Images/searchforce.png" width:"50px" height:"30px"/></a>
        </td>
              
    </tr>
</table>

PhoenixWeb.Site/Views/Member/Message.cshtml
@{
    ViewBag.Title = "Message";
}

<h4>@ViewBag.Msg</h4>