PhoenixWeb/Controllers/QantasProcessingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using Phoenix_BusLog.TransactionHost.Model;
using System.Web.Http;
using PhoenixWeb.Models.ViewModel;
using System.Web.Mvc;
using log4net;
using PhoenixWeb.Helper;
using PhoenixWeb.Models;
using Phoenix_BusLog.Data;
using Phoenix_Service;
using System.Dynamic;
using System.Text;
using DotNetOpenAuth.Messaging;
using OfficeOpenXml;
using Newtonsoft.Json;
using PhoenixWeb.Common;
using Phoenix_BusLog;
using PhoenixObjects.Enums;

namespace PhoenixWeb.Controllers
{
    public class QantasProcessingController : Controller
    {
        private ILog logger = LogManager.GetLogger("QantasProcessingController");

        public const string SaleAndFinRejectedStatus = "SF_REJECTED";
        public const string SaleAndFinApprovalStatus = "SF_APPROVAL";
        public const string ManagerRejectedStatus = "MNG_REJECTED";


        //
        // GET: /QantasProcessing/

        public ActionResult Index(bool isManager)
        {
            var model = new QantasPointApprovalScreenVM();
            model.Years = Enumerable.Range(DateTime.Now.Year - 9, 10).ToList().AsSelectListItems();
            model.Year = DateTime.Now.Year;
            model.Months = DateTimeFormatInfo.CurrentInfo.MonthNames
                .Where(n => !string.IsNullOrEmpty(n))
                .Select((n, i) => new SelectListItem()
                {
                    Text = n,
                    Value = (i + 1).ToString(),
                    Selected = (i + 1) == DateTime.Now.Month
                });
            model.Month = DateTime.Now.Month;

            var companyDA = new CompanyDA();
            var companyList = companyDA.GetCompanyAssociateWithOrganisationforLoyalty();
            model.BusinessTypes = companyList.AsSelectListItems();
            var firstCompany = companyList.FirstOrDefault();
            model.BusinessTypeID = firstCompany == null ? 0 : firstCompany.Company_key;

            if (isManager)
            {
                return View("QantasReviewingForManager", model);

            }
            else
            {
                return View("QantasReviewingForSaleFinance", model);
            }
        }


        public ActionResult QantasPointUpload()
        {
            var model = new QantasPointUploadVM();
            var companyDA = new CompanyDA();
            var companyList = companyDA.GetCompanyAssociateWithOrganisationforLoyalty().OrderBy(x => x.Company_key);
            model.BusinessTypes = companyList.ToList().AsSelectListItems();

            var firstCompany = companyList.FirstOrDefault();
            model.LoyaltyPromotions = firstCompany.LoyaltyPromotions.ToList().AsSelectListItems();

            return View(model);
        }

        public ActionResult QantasPointEarnedRate()
        {
            return View();
        }

        public JsonResult GetExchangeRateTypeList(bool includedGroupType = false)
        {
            IEnumerable<SelectListItem> typeList = null;
            var errorMessage = string.Empty;
            try
            {
                using (TaxiEpayEntities taxiEpayDbContext = new TaxiEpayEntities())
                {
                    if (includedGroupType)
                    {
                        typeList = taxiEpayDbContext.ExchangeRateTypes
                            .Where(x => x.IsActive)
                            .ToList()
                            .AsSelectListItems("GROUP");
                    }
                    else
                    {
                        typeList = taxiEpayDbContext.ExchangeRateTypes
                            .Where(x => x.IsActive && x.ExchangeRateTypeCode != "GROUP")
                            .ToList()
                            .AsSelectListItems();
                    }

                }
            }
            catch (Exception e)
            {
                errorMessage = e.Message;
            }

            var jsonData = new
            {
                IsError = !string.IsNullOrEmpty(errorMessage),
                ErrorMessage = errorMessage,
                Data = typeList
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetQantasPointEarnedRate(QantasPointEarnedRateVM model)
        {
            using (TaxiEpayEntities taxiEpayDbContext = new TaxiEpayEntities())
            {
                var items = taxiEpayDbContext.QBRExchangeRates
                    .Include(x => x.ExchangeRateType)
                    .Include(x => x.QBRPoints)
                    .Where(x => x.IsActive);

                //for sorting
                var qantasServices = new QantasProcessingDA();
                var itemSorter = qantasServices.SortDataListForPointEarnedRate(items, model.SortName, model.SortOrder);

                int totalRecords = itemSorter.Count();
                int totalPages = (int)Math.Ceiling((float)totalRecords / (float)model.PageSize);
                var skip = (model.CurrentPage - 1) * model.PageSize;
                var res = itemSorter.Skip(skip).Take(model.PageSize).ToList();

                var data = res.Select(x => new
                {
                    ID = x.ID,
                    Name = x?.Name,
                    QantasExchangeRate = x?.QantasExchangeRate,
                    Type = x.ExchangeRateType?.ExchangeRateTypeName,
                    FromDate = x.ExchangeRateTypeCode.Equals("NEW_MERCHANT") ? x?.RegisterStartDate?.ToString("dd/MM/yyyy") ?? String.Empty : x?.CampaignStartDate?.ToString("dd/MM/yyyy") ?? String.Empty,
                    ToDate = x.ExchangeRateTypeCode.Equals("NEW_MERCHANT") ? x?.RegisterEndDate?.ToString("dd/MM/yyyy") ?? String.Empty : x?.CampaignEndDate?.ToString("dd/MM/yyyy") ?? String.Empty,
                    x?.ExchangeRateTypeCode,
                    x?.RegisterEffectedDays,
                    IsUsed = x.QBRPoints.Any()
                });

                var jsonData = new
                {
                    total = totalPages,
                    page = model.CurrentPage,
                    records = totalRecords,
                    rows = data
                };

                return Json(jsonData, JsonRequestBehavior.AllowGet);
            }

        }

        public JsonResult UpdateQantasPointEarnedRate(QantasPointEarnedRateVM model)
        {
            var errorMessage = string.Empty;
            try
            {
                if (model == null)
                {
                    throw new Exception("Model is invalid");
                }
                var id = 0;
                using (TaxiEpayEntities taxiEpayDbContext = new TaxiEpayEntities())
                {
                    var qbrExchangeRate = model.ToQbrExchangeRate();

                    var qantasServices = new QantasProcessingDA();
                    id = qantasServices.SaveQantasPointEarnedRate(taxiEpayDbContext, qbrExchangeRate, User.Identity.Name);

                    if (model.ExchangeRateTypeCode == "DEFAULT")
                    {
                        Trace.TraceInformation(id.ToString());
                        taxiEpayDbContext.Database.ExecuteSqlCommand(
                            $"UPDATE dbo.QBRExchangeRate SET IsActive = 0 WHERE ExchangeRateTypeCode = 'DEFAULT' AND ID NOT IN ({id})");
                        taxiEpayDbContext.Database.ExecuteSqlCommand(
                            $"UPDATE dbo.QBRExchangeRate SET IsActive = 1 WHERE ExchangeRateTypeCode = 'DEFAULT' AND ID IN ({id})");
                    }

                }
            }
            catch (Exception e)
            {
                errorMessage = e.Message;
            }

            var jsonData = new
            {
                IsError = !string.IsNullOrEmpty(errorMessage),
                ErrorMessage = errorMessage,
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }


        public JsonResult DeleteQantasPointEarnedRate(int id)
        {
            var errorMessage = string.Empty;
            try
            {
                using (TaxiEpayEntities taxiEpayDbContext = new TaxiEpayEntities())
                {
                    var isExisting = taxiEpayDbContext.QBRExchangeRates.Any(x => x.ID == id);
                    if (isExisting)
                    {
                        var qantasServices = new QantasProcessingDA();
                        qantasServices.DeActiveQantasPointEarnedRate(taxiEpayDbContext, id, User.Identity.Name);

                        taxiEpayDbContext.SaveChanges();
                    }
                    else
                    {
                        throw new Exception("The Exchange Rate doesn't exist.");
                    }
                }
            }
            catch (Exception e)
            {
                errorMessage = e.Message;
            }

            var jsonData = new
            {
                IsError = !string.IsNullOrEmpty(errorMessage),
                ErrorMessage = errorMessage,
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetEarnedRateDateExisting(string startDate, string endDate, string typeCode)
        {
            var errorMessage = string.Empty;
            List<string> typeNameList = new List<string>();
            try
            {
                if (startDate != null && endDate != null && !string.IsNullOrEmpty(typeCode))
                {
                    using (TaxiEpayEntities taxiEpayDbContext = new TaxiEpayEntities())
                    {
                        CultureInfo culture = new CultureInfo("en-US");
                        var startDateTime = DateTime.ParseExact(startDate, "dd/MM/yyyy", culture);
                        var endtDateTime = DateTime.ParseExact(endDate, "dd/MM/yyyy", culture);

PhoenixWeb/Views/QantasProcessing/QantasPointEarnedRate.cshtml
@model PhoenixWeb.Models.ViewModel.VMBaseWithPaging
@{
    ViewBag.Title = "QantasPointEarnedRate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Qantas Point Earned Rate</h2>
<div id="QantasPointEarnedRate">
    <div class="row" style="margin-bottom: 15px;">
        <div class="col-md-12">
            <input id="btnAdd" value="Add New" class="btn btn-primary" type="button" style="float: left;" />
        </div>
    </div>
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-md-12">
            <div class="form-group" id="parentQantasPointEarnedRateGrid">
                <table id="grdQantasPointEarnedRateGrid"></table>
                <div id="grdQantasPointEarnedRateGridPager"></div>
            </div>
        </div>
    </div>
</div>

@Html.Partial("_QantasEarnedRateDialog")

@section scripts
{
    <script src="~/Scripts/pages/Group/PH-EarnedRateDialog.js"></script>
    <script src="~/Scripts/pages/QantasPointReviewing/Services/PH-QantasPointEarnedRateService.js"></script>
    <script src="~/Scripts/pages/QantasPointReviewing/PH-QantasPointEarnedRate.js"></script>
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <script src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery.jqGrid.min.js"></script>
    <style type="text/css">
        #ui-datepicker-div .ui-datepicker-month,
        #ui-datepicker-div .ui-datepicker-month option {
            color: black !important
        }

        #ui-datepicker-div .ui-datepicker-year,
        #ui-datepicker-div .ui-datepicker-year option {
            color: black !important
        }
    </style>
    <script>
        $(document).ready(function () {
            $(".active").removeClass("active open");
            $(".LiveSMS").addClass("active open");
        });
    </script>
}

PhoenixWeb/Views/QantasProcessing/QantasPointReview.cshtml
@using System.Web.Mvc.Html
@using PhoenixWeb.Models.ViewModel;
@model QantasPointFileReviewingVM
@Html.ValidationSummary(true)

<h3 class="page-title">
    Qantas Point File Reviewing
</h3>

@if (Model == null)
{
    return;
}

@using (Html.BeginForm("SentToApproval", "QantasProcessing", FormMethod.Post, new { id = "qantasPointFileReviewing" }))
{
    <form action="#" class="horizontal-form">
        <dfiv class="form-body">
            <input id="QantasExportFileKey" hidden="hidden" type="text" value="" />
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(x => Model.Years, new { @class = "control-labelM col-md-4" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(x => x.Year, Model.Years, new { @class = "form-control option-filter" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(x => Model.Months, new { @class = "control-labelM col-md-4" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(x => x.Month, Model.Months, new { @class = "form-control option-filter" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(x => Model.QantasFileID, new { @class = "control-labelM col-md-4" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(x => x.QantasFileID, Model.QantasFileNameList, new { @class = "form-control option-filter" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="col-md-6">
                        <span style="float:left;font-size:small">
                            <button type="button" class="btn blue-chambray" id="search"><i class="fa fa-check"></i> Load QBR</button>
                        </span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px; display: none" id="filterSection">
                <div style="position: relative; float: right;  width: 15%; margin-right: 1%;">
                    <i class="glyphicon glyphicon-search" style="position: absolute;pointer-events: none; padding: 10px; right: 0px;"></i>
                    <input id="textAdvanceSearch" title="Filter Member ID, QBR Number, Status, Comment" type="text" class="form-control" placeholder="Search..." />
                </div>
            </div>
            <div class="row" style="margin-bottom: 20px;">
                <div class="col-md-12">
                    <div class="form-group" id="parentQantasPointFileVerificationGrid">
                        <table id="grdQantasPointFileVerification"></table>
                        <div id="grdQantasPointFileVerificationPager"></div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 20px;">
                <div class="col-md-12">
                    <button type="button" style="float: right;" class="btn blue-chambray" onclick="ExportFile()">Generate to Excel</button>
                </div>
            </div>
        </dfiv>
    </form>
}
@section scripts {
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <script src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery.jqGrid.min.js"></script>
    <script src="~/Scripts/pages/QantasPointFileReviewing/PH-QantasPointFileReviewing.js"></script>
    <script src="~/Scripts/pages/QantasPointFileReviewing/PH-QantasPointFileReviewingService.js"></script>
    <style type="text/css">
        </style>
    <script>
        $(document).ready(function () {
            $(".active").removeClass("active open");
            $(".QantasReviewing").addClass("active open");
        });
    </script>
}

PhoenixWeb/Views/QantasProcessing/QantasPointUpload.cshtml
@using System.Web.Mvc.Html
@model PhoenixWeb.Models.ViewModel.QantasPointUploadVM
@{
    ViewBag.Title = "Qantas Point Upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3 class="page-title">
    Qantas Point Upload
</h3>
<form id="QantasPointUpload">
    <input type="hidden" id="urlHidden" value="@Url.Content("~/")">
    <div class="form-body">
        <div class="row" style="margin-bottom: 15px;">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(x => Model.BusinessTypes, new { @class = "control-labelM col-md-4" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(x => x.BusinessTypeId, Model.BusinessTypes, new { @class = "form-control option-filter" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-bottom: 15px;">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(x => Model.LoyaltyPromotions, new { @class = "control-labelM col-md-4" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(x => x.LoyaltyPromotionId, Model.LoyaltyPromotions, new { @class = "form-control option-filter" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-bottom: 15px;">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.Label("Upload Qantas Point file", new { @class = "control-labelM col-md-4" })
                    <div class="col-md-6">
                        <input type="file" name="" title="Upload Qantas Point file" id="btnChooseFile" class="form-control">
                    </div>
                    <input type="button" title="Load data from file to grid view." value="Load File" class="btn btn-default" id="btnLoadFile">
                </div>
            </div>
        </div>
        <div class="row" style="margin-bottom: 20px;">
            <div class="col-md-12">
                <div class="form-group" id="parentQantasPointUploadGrid">
                    <table id="grdQantasPointUploadGrid"></table>
                    <div id="grdQantasPointUploadGridPager"></div>
                </div>
            </div>
        </div>
        
        <div class="row" style="margin-bottom: 20px;">
            <div class="col-md-12">
                <button id="btnSave" class="form-control btn btn-primary" style="width: 5%;" disabled="disabled">Save</button>
            </div>
        </div>
    </div>
</form>
@section scripts
{
    <script src="~/Scripts/pages/QantasPointReviewing/PH-QantasPointUpload.js"></script>
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <script src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery.jqGrid.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".active").removeClass("active open");
            $(".QantasReviewing").addClass("active open");
        });
    </script>
}

PhoenixWeb/Views/QantasProcessing/QantasReviewingForManager.cshtml
@using System.Web.Mvc.Html
@using PhoenixWeb.Models.ViewModel;
@model QantasPointApprovalScreenVM
@Html.ValidationSummary(true)

<h3 class="page-title">
    Qantas Point Approval
</h3>

@if (Model == null)
{
    return;
}

@using (Html.BeginForm("SentToQantas", "QantasProcessing", FormMethod.Post, new { id = "QantasPointReviewingForManager" }))
{
    <input type="hidden" id="urlHidden" value="@Url.Content("~/")">
    <form action="#" class="horizontal-form">
        <div class="form-body">
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(x => Model.Years, new { @class = "control-labelM col-md-4" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(x => x.Year, Model.Years, new { @class = "form-control option-filter" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(x => Model.Months, new { @class = "control-labelM col-md-4" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(x => x.Month, Model.Months, new { @class = "form-control option-filter" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(x => Model.BusinessTypes, new { @class = "control-labelM col-md-4" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(x => x.BusinessTypeID, Model.BusinessTypes, new { @class = "form-control option-filter" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="col-md-6">
                        <span style="float:left;font-size:small">
                            <button type="button" class="btn blue-chambray" id="search"><i class="fa fa-check"></i> Load QBR</button>
                        </span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-1"></div>
                <div class="col-md-2">Total Transaction: <label id="totalTransaction"> </label></div>
                <div class="col-md-2">Total Approval: <label id="totalApproval"> </label></div>
                <div class="col-md-2">Total Rejected: <label id="totalRejected"> </label></div>
                <div class="col-md-3">Total Point: <label id="totalPoint"> </label></div>
            </div>
            <div class="row" style="margin-bottom: 15px; display: none" id="filterSection">
                <div style="position: relative; float: right;  width: 15%; margin-right: 1%;">
                    <i class="glyphicon glyphicon-search" style="position: absolute;pointer-events: none; padding: 10px; right: 0px;"></i>
                    <input id="textAdvanceSearch" title="Filter Member ID, QBR Number, Status, Comment, Trading Name" type="text" class="form-control" placeholder="Search..." />
                </div>
            </div>
            <div class="row" style="margin-bottom: 20px;">
                <div class="col-md-12">
                    <div class="form-group" id="parentQantasPointVerificationForManagerGrid">
                        <table id="grdQantasPointVerificationForManager"></table>
                        <div id="grdQantasPointVerificationForManagerPager"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <span style="float:left;font-size:small">
                        <button type="button" class="btn blue-chambray" id="Reject" onclick="onManagerRejectQantasPointReward()"><i class="fa fa-check"></i>Reject</button>
                    </span>
                </div>
                <div class="col-md-6">
                    <span style="float: right; font-size: small">
                        <button type="button" class="btn blue-chambray" onclick="ExportFile()">Generate to Excel</button>
                        <button type="button" class="btn blue-chambray" id="sentToQantas" onclick="sendQBRToQantas()"><i class="fa fa-check"></i>Sent to Qantas</button>
                    </span>
                </div>
            </div>
        </div>
    </form>
}
@section scripts {
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <script src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery.jqGrid.min.js"></script>
    <script src="~/Scripts/pages/QantasPointReviewing/PH-QantasPointReviewingForManager.js"></script>
    <style type="text/css">
        </style>
    <script>
        $(document).ready(function () {
            $(".active").removeClass("active open");
            $(".QantasReviewing").addClass("active open");
        });
    </script>
}

PhoenixWeb/Views/QantasProcessing/QantasReviewingForSaleFinance.cshtml
@using System.Web.Mvc.Html
@using PhoenixWeb.Models.ViewModel;
@model QantasPointApprovalScreenVM
@Html.ValidationSummary(true)

<h3 class="page-title">
    Qantas Point Reviewing For Sale/Finance
</h3>
@*<div class="portlet box blue">
        @*<div class="portlet-title">
            <div class="caption">
                <i class="fa fa-adjust"></i>
                Process declined transaction for the month of @DateTime.Now.ToString("MMMM yyyy")
            </div>
            <div class="tools">
                <a href="" class="collapse"></a>
                <a href="" class="reload">
                </a>
            </div>
        </div>
    </div>*@

@if (Model == null)
{
    return;
}

@using (Html.BeginForm("SentToApproval", "QantasProcessing", FormMethod.Post, new { id = "QantasPointReviewingForSaleFin" }))
{
    <input type="hidden" id="urlHidden" value="@Url.Content("~/")">
    <form action="#" class="horizontal-form">
        <div class="form-body">
            <input id="QantasExportFileKey" hidden="hidden" type="text" value="" />
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(x => Model.Years, new { @class = "control-labelM col-md-4" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(x => x.Year, Model.Years, new { @class = "form-control option-filter" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(x => Model.Months, new { @class = "control-labelM col-md-4" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(x => x.Month, Model.Months, new { @class = "form-control option-filter" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(x => Model.BusinessTypes, new { @class = "control-labelM col-md-4" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(x => x.BusinessTypeID, Model.BusinessTypes, new { @class = "form-control option-filter" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px;">
                <div class="col-md-6">
                    <div class="col-md-6">
                        <span style="float:left;font-size:small">
                            <button type="button" class="btn blue-chambray" id="search"><i class="fa fa-check"></i> Load QBR</button>
                        </span>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-bottom: 15px; display: none" id="filterSection">
                <div style="position: relative; float: right;  width: 15%; margin-right: 1%;">
                    <i class="glyphicon glyphicon-search" style="position: absolute;pointer-events: none; padding: 10px; right: 0px;"></i>
                    <input id="textAdvanceSearch" title="Filter Member ID, QBR Number, Status, Comment, TradingName" type="text" class="form-control" placeholder="Search..." />
                </div>
            </div>
            <div class="row" style="margin-bottom: 20px;">
                <div class="col-md-12">
                    <div class="form-group" id="parentQantasPointVerificationForSaleFinGrid">
                        <table id="grdQantasPointVerificationForSaleFin"></table>
                        <div id="grdQantasPointVerificationForSaleFinPager"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <span style="float:left;font-size:small">
                        <button type="button" class="btn blue-chambray" id="Approve" onclick="onApproveQantasPointReward()"><i class="fa fa-check"></i>Approve</button>
                        <button type="button" class="btn blue-chambray" id="Reject" onclick="onRejectQantasPointReward()"><i class="fa fa-check"></i>Reject</button>
                    </span>
                </div>
                <div class="col-md-6">
                    <span style="float: right; font-size: small">
                        <button type="button" class="btn blue-chambray" onclick="ExportFile()">Generate to Excel</button>
                        <button type="button" class="btn blue-chambray" id="sentToApproval" onclick="sendQantasPointToApproval()"><i class="fa fa-check"></i>Sent to Approval</button>
                    </span>
                </div>
            </div>
        </div>
    </form>
}
@section scripts {
    <link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
    <script src="~/Scripts/i18n/grid.locale-en.js"></script>
    <script src="~/Scripts/jquery.jqGrid.min.js"></script>
    <script src="~/Scripts/pages/QantasPointReviewing/PH-QantasPointReviewingForSaleFin.js"></script>
    <style type="text/css">
        </style>
    <script>
        $(document).ready(function () {
            $(".active").removeClass("active open");
            $(".QantasReviewing").addClass("active open");
        });
    </script>
}