PhoenixWeb/Controllers/MemberSignUpController.cs
using Phoenix_BusLog.Data;
using PhoenixObjects.Financial;
using PhoenixObjects.Member;
using PhoenixWeb.ActionFilters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhoenixWeb.Controllers
{
    [Authorize]
    public class MemberSignUpController : PhoenixWebController
    {
        //
        // GET: /MemberSignUp/

        public ActionResult Index()
        {
            return View("Menu");
        }
      
        //
        // GET: /MemberSignUp/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /MemberSignUp/Create
        public ActionResult AutoCompleteEftTerminalId(string term)
        {
            List<string> m = new List<string>();
            TerminalDA cda = new TerminalDA();
            var model = cda.GetEftTerminals(term).ToList();
            foreach (var p in model)
            {
                m.Add(p);
            }
            return Json(m, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Create()
        {
            MemberModel model = new MemberModel();
            DrawDropDownConfig(model.CompanyKey);
            DrawDropDownConfigAllocateTerminal();
            return View(model);
        }
        private void DrawDropDownConfigAllocateTerminal()
        {
            StateDA sda = new StateDA();
            var states = sda.GetStateAustralia().ToList();
            ViewBag.StateList = states.Select(item => new SelectListItem
            {
                Text = item.StateName,
                Value = item.StateKey.ToString()
            }).ToList();

            VehicleTypeDA cda = new VehicleTypeDA();
            var VehicleType = cda.Get().ToList();
            ViewBag.VehicleTypeList = VehicleType.Select(item => new SelectListItem
            {

                Text = item.Name,
                Value = item.VehicleType_key.ToString()
            }).ToList();
        }
        private void DrawDropDownConfig(int company_key)
        {
            MemberRentalTemplateDA cda = new MemberRentalTemplateDA();
            var MemberRentalTemplateList = cda.GetByCompanyKey(company_key).ToList();

            ViewBag.MemberRentalTemplateList = MemberRentalTemplateList.Select(item => new SelectListItem
            {
                Text = item.Description,
                Value = item.MemberRentalTemplateKey.ToString()
            }).ToList();

            BusinessTypeDA bda = new BusinessTypeDA();
            var BusinessTypeList = bda.Get().ToList();
            ViewBag.BusinessTypeList = BusinessTypeList.Select(item => new SelectListItem
            {
                Text = item.BusinessTypeName,
                Value = item.BusinessTypeKey.ToString()
            }).ToList();
        }
        //
        // POST: /MemberSignUp/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /MemberSignUp/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /MemberSignUp/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /MemberSignUp/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /MemberSignUp/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PhoenixWeb/Views/MemberSignUp/Create.cshtml
@model PhoenixObjects.Member.MemberModel

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm("Create", "MemberSignUp", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    @Html.ValidationMessage("error")
<h3 class="page-title">
    Sign Up Member
    <small>insert new member</small>
</h3>

<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-adjust"></i>
            Member Information
        </div>
        <div class="tools">
            <a href="" class="expand">
            </a>
            <a href="" class="reload">
            </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form action="#" class="horizontal-form">
            <div class="form-body">
                <h3 class="form-section">Member Info</h3>
              
                @*<div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.IsBankCustomer, new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.CheckBoxFor(model => model.IsBankCustomer, new { id = "IsBankCustomer" })
                                <span class="help-block">
                                    @Html.ValidationMessageFor(model => model.IsBankCustomer)
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.IsCashCustomer, new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.CheckBoxFor(model => model.IsCashCustomer, new { id = "IsCashCustomer" })
                                <span class="help-block">
                                    @Html.ValidationMessageFor(model => model.IsCashCustomer)
                                </span>
                            </div>
                        </div>
                    </div>
                </div>*@
                <div class="row">
                    <!--/span-->
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.Label("Business Type", new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.DropDownListFor(model => model.CompanyKey, (IEnumerable<SelectListItem>)ViewBag.BusinessTypeList, new { id = "BusinessType", @class = "form-control" })
                                <span class="help-block">
                                    @Html.ValidationMessageFor(model => model.CompanyKey)
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.Label("Business State", new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.DropDownListFor(model => model.State_key, (IEnumerable<SelectListItem>)ViewBag.StateList, new { id = "State", @class = "form-control" })
                                <div class="col-md-9">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--/row-->
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", id = "FirstName" })
                            </div>
                        </div>
                    </div>
                    <!--/span-->
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(model => model.LastName, new { @class = "form-control", id = "LastName" })
                                <span class="help-block">
                                    @Html.ValidationMessageFor(model => model.LastName)
                                </span>
                            </div>
                        </div>
                    </div>
                    <!--/span-->
                </div>
                <!--/row-->
          
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.Label("Terminal Id", new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                <input type="text" class="form-control" name="EftTerminal_key" required id="EftTerminal_key" placeholder="type id and select" />

                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.PhotoID, new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                <input type="file" name="file" id="file" />
                                <span class="help-block">
                                    @Html.ValidationMessageFor(model => model.PhotoID)
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-actions right">
                <button type="button" class="btn default">Cancel</button>
                <button type="submit" class="btn blue"><i class="fa fa-check"></i> Save</button>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>
}
@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $("#EftTerminal_key").autocomplete({
                source: '@Url.Action("AutoCompleteEftTerminalId")'
            });
        });
    </script>
}

PhoenixWeb/Views/MemberSignUp/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $(".active").removeClass("active open");
            $(".Member").addClass("active open");
        });

    </script>
}

PhoenixWeb/Views/MemberSignUp/Menu.cshtml
@{
    ViewBag.Title = "Menu";
}
<table cellpadding:"5" align="center">
    <tr>
        <td>
            <a href="@Url.Action("Create", "MemberSignUp")"><img id="CreateMember" src="~/Images/ICONS/AddMember.png" /></a>
        </td>
      
    </tr>
</table>
@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $(".active").removeClass("active open");
            $(".Member").addClass("active open");
        });

    </script>
}